name: "Validate flake & check formatting"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  nix-flake-check:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command cargo test
